### ISSUE TITLE
Decimal without 0

### ISSUE THREAD

**Issue by LecksC** [Krzmbrzl/SQDev#129]
`_ctrl ctrlCommit .4; ` gives the odd error:

> no viable alternative at input '_ctrlctrlCommit.' fn_FadeAndDelete.sqf  line 11 Problem

`_ctrl ctrlCommit 0.4; ` works. Both are valid.

**Comment by Krzmbrzl** [comment]
Yes you are right. I never thought about it but it has to be changed in the used grammar.
Thanks for reporting!

**Comment by Krzmbrzl** [comment]
Okay I implemented it but it will only ship with the next update that should come out somewhen soon.
See the 0.7.2 milestone for progress inforation ;)
