### ISSUE TITLE
Wrong problem detection

### ISSUE THREAD

**Issue by quequiere** [Krzmbrzl/SQDev#144]
Hello, 
An error is detected on a clean code.
Code is 
`[tempPhone] remoteExec ["qqphone_networking_fnc_refreshPhoneNumberClient", _senderId];`

And the error is detected on 
`["qqphone_networking_fnc_refreshPhoneNumberClient", _senderId];`

Saying that "Expected  but got "Array"!

The code work perfectly.

Screenshot include
![sans titre](https://user-images.githubusercontent.com/2946661/29492985-a67aad86-858c-11e7-9f8d-2fbc14a9cf4c.png)

**Comment by Krzmbrzl** [comment]
Thanks for reporting! 
On the first glaube it appears to me that there is a problem during the determination of the return value of the argument of `remoteExec`. 

I'll have a look at this...

**Comment by Krzmbrzl** [comment]
No actually when thinking about it the return value is detected just fine... It's the stored data type for `remoteExec` that seems to have some problems.

Could you create and attach a plugin-info (via the button in the toolbar with the exclamationmark on the green background)?

**Comment by quequiere** [comment]
Ok :) 
[SQDevPluginInfo.zip](https://github.com/Krzmbrzl/SQDev/files/1237079/SQDevPluginInfo.zip)

One more question, how can i format my code (auto indent) with your plugin ?  Or a way to use tm4_indenter

**Comment by Krzmbrzl** [comment]
Formatting is not yet implemented. Currently everything has to be formatted by hand. 

And the thing you mentioned I don't know it so I'm afraid I can't help you with that one :/

**Comment by quequiere** [comment]
It's a tool with posseidon that formating directly files (with a command line), i'll try to find a way to launch the formating from the eclipse executor. I did it for auto compile source to pbo from eclipse and export them the server folders

But thx :)

**Comment by Krzmbrzl** [comment]
Alright I tracked the bug down to it's source and it will be removed in the next version.

However if it bugs you, you can fix the smyptoms of that particular side of the bug you discoverd by hand:

1. Go to your eclipse workspace-folder and make sure your explorer shows hidden files to you
2. Go to `.metadata -> .plugins -> raven.sqdev.util -> resources`
3. Open the `SQFKeywords.txt`
4. Find the part that says
```
<Keyword>
	remoteExec
</Keyword>
```
5. Somwhere under that point there should be a part that looks like this:
```
<Syntax>
	Anything remoteExec Array;
</Syntax>
```
Remove the trailing semiclon after `Array`, save the file and restart eclipse

6. Be happy as the error marker should be gone
