### ISSUE TITLE
Bug in linter

### ISSUE THREAD

**Issue by Krzmbrzl** [Krzmbrzl/SQDev#162]
```
#define PRIVATE(var, val) (private var = val) PRIVATE(_a, 6);
```
 produces the error
```
 "Invalid expression in context of "private"" and "',' outside of array context!"
```

**Comment by Krzmbrzl** [comment]
```
#define SET_START(name) missionNameSpace setVariable[name, #define SET_END ] SET_START("myFunc") { params ["_one"]; } SET_END;
```
does also produce an error

**Comment by Sparker95** [comment]
Hope that this helps:
So If I try to set the variable to a number instead of a more complicated CODE statement with this code:
```
#define SET_START(name) missionNameSpace setVariable[name,
#define SET_END ]

SET_START("myVar")
3
SET_END;
```
The linter produces an error around the '3' statement, saying I need a ; after the '3'. If I put the ; then the linter is totally satisfied.

**Comment by Krzmbrzl** [comment]
Ah okay now I understand what the problem is: The plugin can't handle this kind of preprocessor-magic as it is not really preprocessing the code at all.

The only things it does allow are preprocessor statements in the code (started by `#`) and the usage of macros (possibly with argument) that don't need to be terminated by a semicolon.

Therefore it considers your code as `Macro`, `statement`, `Macro` and as each statement has to be terminated by a semicolon in order to allow a new statement (or Macro in that case) it complains.

But as I said before: This could only be resolved by implementing a proper preprocessor, but before that can be tackled #72 has to be implemented as the preprocessing couldn't resolve some paths and would get really messy otherwise...

**Comment by Krzmbrzl** [comment]
I don't get any error messages for `#define PRIVATE(var, val) (private var = val) PRIVATE(_a, 6);` at all.

Do you also get an error message if pasting only that line in an editor?

**Comment by Sparker95** [comment]
Yes I get an error but your example is a bit wrong. It should be like this:
```
#define PRIVATE(var, val) private var = val
PRIVATE(_a, 6);
```

**Comment by Krzmbrzl** [comment]
Ah okay I see. Now I get the error with the `,` being outside of an array context.

Thanks for the clarification :+1:
