### ISSUE TITLE
Assignment operator doesn't always check variable existance

### ISSUE THREAD

**Issue by Sparker95** [Krzmbrzl/SQDev#168]
For example, if I have variables `_a`, `_b` and `_c` which have not been defined anywhere.
``private _a = _b;`` -  displays no error
``private _a = _b + _c;`` - displays the proper error: undefined local variable `_b`, `_c`

**Comment by Krzmbrzl** [comment]
It turned out that nular expressions in assignments weren't validated in general... This problem should now be fixed though

**Comment by Sparker95** [comment]
Hi! I don't start a new issue because I think this might be related.
So, it turns out that expressions passed as macro arguments are not validated. For example:
```
		#define MY_MACRO(a) (a+3)
		private _b = MY_MACRO(_c + 3); // _c is not defined anywhere and doesn't exist
```
does not produce an error, although `private _b = _c + 3;` will produce an error.

Another similar thing I have noticed: when we create an array the passed values are not checked as well. For example:
`private _b = [4, _c]; // _c is not defined before` gives no error, but `private _b = [4, _c + 3];` gives an error (_c is undefined). Also, what is strange, when we call a function the expressions inside the array are checked properly: `[4, _c] call global_func;` gives an error.

**Comment by Krzmbrzl** [comment]
Macro arguments aren't checked at all as there is no way to determine whether it will be valid or not without actually fully preprocessing all files.

This might be fixed with the implementation of #165 though

**Comment by Sparker95** [comment]
Hmm yes I agree with you. Because a macro can have some concatenation happening inside it.

What do you think about the array problem though?

**Comment by Krzmbrzl** [comment]
That has to be investigated further as it should not be that way.

I'll reopen this issue until I have properly checked everything and maybe open an extra issue for that matter...

**Comment by Krzmbrzl** [comment]
`private _b = [4, _c];` errors on my machine... I am pretty sure that the root for this bug was indeed the same as for the `_b = _c` thing. Therefore this issue has been fixed alongside of it.
