### ISSUE TITLE
Wizard for mission scripting 

### ISSUE THREAD

**Issue by thumpnail** [Krzmbrzl/SQDev#169]
A popup, after you clicked on new projekt/ new mission projekt, where you can pick the path for your mission.

So you create a mission inside arma 3 and save it there. with the popup for new mission you can pick the path of the mission folder or the mission inside a ui with dropdown and #start scripting inside eclipse.
and the whole mission folder structure is visible in eclipse. like if you choose a folder inside vs code.

**Comment by Krzmbrzl** [comment]
I believe what you are referring to is already implemented as `Import project`. See [the manual](http://krzmbrzl.github.io/SQDev/resources/SQDev.pdf#section.2.3) for further description.

If this is not what you mean or if it doesn't fulfill all your needs, please report back with further information on what you'd like to see implemented differently/additionally :)

**Comment by thumpnail** [comment]
ups ok nvm

**Comment by Krzmbrzl** [comment]
Alright, then I'll close this issue as solved :+1:
