### ISSUE TITLE
Macro with brackets but no parameters: error

### ISSUE THREAD

**Issue by Sparker95** [Krzmbrzl/SQDev#171]
Hi!
For instance, I am creating a macro like this:
```
#define MYMACRO() 3
private _a = MYMACRO();
```
And it gives the following error at line 2:
`The operator "MYMACRO" can not be used as a binary operator!`
If I create a more proper macro with input arguments like this:
```
#define MYMACRO(a) (3+a)
private _a = MYMACRO(2);
```
Then SQDEV doesn't produce this error any more.

**Comment by jokoho48** [comment]
that is correct macros without parameters don't have brackets and throw an error.
the correct use is
```sqf
#define MYMACRO 3
private _a = MYMACRO;
```

**Comment by Sparker95** [comment]
But the game's preprocessor accepts this macro without any issues.
I believe Arma's preprocessor is derived from the C preprocessor. Such a macro also works well in C, I think they call it 'Function-like macros':
https://gcc.gnu.org/onlinedocs/cpp/Function-like-Macros.html#Function-like-Macros

**Comment by Krzmbrzl** [comment]
Even if the game didn't accept this macro, the error message should be generated at the correct position and with an actually helpful text...

**Comment by Krzmbrzl** [comment]
Okay I decided to not error on this one at all. Though the preprocessor to be implemented might do that...
For now I consider this issue to be fixed
